# Generated by Django 4.0.4 on 2026-02-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0002_alter_book_id_alter_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
