# Generated by Django 4.0.4 on 2026-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redbus', '0003_remove_book_email_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='busid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='nos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='nos',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bus',
            name='rem',
            field=models.IntegerField(),
        ),
    ]
